# Configuration principale du chart mailstack
global:
  namespace: email-stack

# Labels et annotations communes
commonLabels:
  app.kubernetes.io/part-of: mailstack
  
commonAnnotations:
  description: "Complete email stack with mailserver and roundcube"

# Configuration du serveur mail
mailserver:
  enabled: true
  
  image:
    repository: ghcr.io/docker-mailserver/docker-mailserver
    tag: "13.3.1"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  # Ports du serveur mail
  ports:
    smtp: 25
    imap: 143
    imaps: 993
    submission: 587
    smtps: 465
  
  # Configuration du service
  service:
    type: ClusterIP
    annotations: {}
  
  # Comptes email (utilisateurs) créés au déploiement
  accounts:
    - email: "user1@mail.local"
      password: "password123"
    - email: "user2@mail.local"
      password: "password456"
    - email: "jojo@mail.local"
      password: "jojo"  
  # Comptes email supplémentaires (optionnel)
  # Chaque ligne suit le format : adresse|{PLAIN}motdepasse
  extraAccounts: |
    # jojo@mail.local|{PLAIN}jojo
    # bob@mail.local|{PLAIN}motdepasseBob
  
  # Alias email
  aliases:
    - alias: "admin@mail.local"
      target: "user1@mail.local"
  
  # Configuration des volumes
  persistence:
    enabled: true
    storageClass: "standard"
    size: 10Gi
  
  # Variables d'environnement
  env:
    HOSTNAME: "mailserver.mail.local"
    DOMAINNAME: "mail.local"
    POSTFIX_INET_PROTOCOLS: "ipv4"
    ONE_DIR: "1"
    ENABLE_RSPAMD: "0"
    ENABLE_CLAMAV: "0"
    ENABLE_FAIL2BAN: "0"
    ENABLE_AMAVIS: "0"   # Désactive Amavis
    PERMIT_DOCKER: "connected-networks"
    OVERRIDE_HOSTNAME: "mailserver.mail.local"
  
  # Ressources
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Configuration Roundcube
roundcube:
  enabled: true
  
  # Instance unique Roundcube
  instance1:
    enabled: true
    name: "roundcube"
    replicaCount: 1
    
    image:
      repository: roundcube/roundcubemail
      tag: "1.6.11-apache"
      pullPolicy: IfNotPresent
    
    config:
      dbType: "sqlite"
      uploadMaxFilesize: "20M"
      desKey: "rcmail-user1-des-key-12345678901234567890"
    
    service:
      type: NodePort
      port: 80
      nodePort: 30081
      annotations: {}
    
    persistence:
      enabled: true
      storageClass: "standard"
      size: 2Gi
    
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  
  # Instance 2 désactivée
  instance2:
    enabled: false
    name: "roundcube-user2"
    replicaCount: 1
    
    image:
      repository: roundcube/roundcubemail
      tag: "1.6.11-apache"
      pullPolicy: IfNotPresent
    
    config:
      dbType: "sqlite"
      uploadMaxFilesize: "20M"
      desKey: "rcmail-user2-des-key-09876543210987654321"
    
    service:
      type: NodePort
      port: 80
      nodePort: 30082
      annotations: {}
    
    persistence:
      enabled: true
      storageClass: "standard"
      size: 2Gi
    
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

# Secret pour les comptes
secret:
  enabled: true

# Sélecteur de nœuds, affinité et tolérances
nodeSelector: {}
affinity: {}
tolerations: []
