{{- if .Values.mailserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mailstack.mailserver.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # Configuration Postfix
  postfix-main.cf: |
    # Configuration de base pour Postfix
    smtpd_banner = $myhostname ESMTP
    biff = no
    append_dot_mydomain = no
    readme_directory = no
    compatibility_level = 3.6
    
    # Domaines
    myhostname = {{ .Values.mailserver.env.HOSTNAME }}
    mydomain = {{ .Values.mailserver.env.DOMAINNAME }}
    myorigin = $mydomain
    mydestination = localhost.$mydomain, localhost, $myhostname, $mydomain
    
    # Réseaux autorisés
    mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
    
    # Taille des messages
    message_size_limit = 26214400
    mailbox_size_limit = 1073741824
    
    # Configuration SASL
    smtpd_sasl_auth_enable = yes
    smtpd_sasl_type = dovecot
    smtpd_sasl_path = private/auth
    smtpd_sasl_security_options = noanonymous
    smtpd_sasl_local_domain = $myhostname
    broken_sasl_auth_clients = yes
    
    # Configuration TLS
    smtpd_use_tls = yes
    smtpd_tls_security_level = may
    smtpd_tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem
    smtpd_tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
    smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
    smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
    
    # Restrictions
    smtpd_recipient_restrictions = permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination
    smtpd_sender_restrictions = permit_sasl_authenticated,permit_mynetworks
    
    # Mailboxes virtuels
    virtual_mailbox_domains = {{ .Values.mailserver.env.DOMAINNAME }}
    virtual_mailbox_base = /var/mail
    virtual_mailbox_maps = hash:/tmp/docker-mailserver/postfix-accounts.cf
    virtual_alias_maps = hash:/tmp/docker-mailserver/postfix-aliases.cf
    virtual_uid_maps = static:5000
    virtual_gid_maps = static:5000

  # Configuration Dovecot
  dovecot.conf: |
    # Configuration de base
    protocols = imap pop3 lmtp
    listen = *, ::
    login_greeting = Dovecot ready.
    
    # Authentification
    auth_mechanisms = plain login
    disable_plaintext_auth = no
    
    # SSL/TLS
    ssl = yes
    ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
    ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key
    ssl_protocols = !SSLv3 !TLSv1 !TLSv1.1
    
    # Mailboxes
    mail_location = maildir:/var/mail/%d/%n/Maildir
    mail_uid = 5000
    mail_gid = 5000
    
    # Services
    service auth {
      unix_listener /var/spool/postfix/private/auth {
        mode = 0666
        user = postfix
        group = postfix
      }
    }
    
    service auth-worker {
      user = vmail
    }
    
    service lmtp {
      unix_listener /var/spool/postfix/private/dovecot-lmtp {
        mode = 0600
        user = postfix
        group = postfix
      }
    }
    
    # Base de données des utilisateurs
    userdb {
      driver = passwd-file
      args = username_format=%u /tmp/docker-mailserver/postfix-accounts.cf
    }
    
    passdb {
      driver = passwd-file
      args = username_format=%u /tmp/docker-mailserver/postfix-accounts.cf
    }
{{- end }}
