apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-apache-exporter
  labels:
    app.kubernetes.io/name: apache-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apache-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apache-exporter
    spec:
      containers:
        - name: apache-exporter
          image: lusotycoon/apache-exporter:v0.11.0
          ports:
            - containerPort: 9117
          env:
            - name: SCRAPE_URI
              value: "http://web-apache-web-apache.web-apache.svc.cluster.local:80/server-status?auto"
          args:
            - "--scrape_uri=$(SCRAPE_URI)"
            - "--telemetry.address=0.0.0.0:9117"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
