apiVersion: v1
kind: Service
metadata:
  name: bind9-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: bind9-exporter
spec:
  ports:
    - name: metrics
      port: {{ .Values.bind9.service.port }}
      targetPort: {{ .Values.bind9.service.port }}
  selector:
    app: bind9-exporter
