apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-service
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      {{- if .Values.grafana.service.nodePort }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "monitoring.fullname" . }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}