apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-nginx-exporter
  labels:
    app.kubernetes.io/name: nginx-exporter
spec:
  selector:
    app.kubernetes.io/name: nginx-exporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
  type: ClusterIP
