apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-blackbox-config
data:
  config.yml: |
    modules:
      dns_test:
        prober: dns
        dns:
          query_name: "google.com"
          query_type: "A"
          valid_rcodes:
            - NOERROR
          transport_protocol: "udp"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-dns-monitor
  labels:
    app.kubernetes.io/name: dns-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dns-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dns-monitor
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        ports:
        - containerPort: 9115
        args:
        - "--config.file=/etc/blackbox_exporter/config.yml"
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: {{ include "monitoring.fullname" . }}-blackbox-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-dns-monitor
  labels:
    app.kubernetes.io/name: dns-monitor
spec:
  selector:
    app.kubernetes.io/name: dns-monitor
  ports:
  - protocol: TCP
    port: 9115
    targetPort: 9115
  type: ClusterIP
