apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus-service
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - name: web
      port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
      {{- if .Values.prometheus.service.nodePort }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "monitoring.fullname" . }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}