{{- $rootPass := required "Vous devez définir .Values.mysqlRootPassword (ex: --set mysqlRootPassword=...)" .Values.mysqlRootPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ $rootPass | quote }}
