apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mysql.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
