replicaCount: 3
image:
  repository: ubuntu/bind9
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: NodePort
  port: 53
  nodePort: 31055
namespace:
  create: false
  name: bind9  # ✅ Nouveau nom de namespace
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
securityContext:
  runAsUser: 0
  privileged: true
  capabilities:
    add:
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
dns:
  forwarders:
    - "8.8.8.8"
    - "8.8.4.4"
  
  zones:
    test.local:  # ✅ Nom correct
      ttl: 604800
      serial: 2
      admin: "admin.test.local"
      ns: "ns1.test.local"
      records:
        - name: "@"
          type: "A"
          value: "192.168.49.2"
        - name: "ns1"
          type: "A"
          value: "192.168.49.2"
        - name: "web"
          type: "A"
          value: "192.168.49.2"
        - name: "nginx"
          type: "A"
          value: "192.168.49.2"
        - name: "phpmyadmin"
          type: "A"
          value: "192.168.49.2"
        - name: "webmail"
          type: "A"
          value: "192.168.49.2"
        - name: "monitoring"
          type: "A"
          value: "192.168.49.2"
    
    monsite.local:  # ✅ Nom correct
      ttl: 604800
      serial: 2
      admin: "admin.monsite.local"
      ns: "ns1.monsite.local"
      records:
        - name: "@"
          type: "A"
          value: "192.168.49.2"  # ✅ IP correcte
        - name: "ns1"
          type: "A"
          value: "192.168.49.2"
        - name: "dev"
          type: "A"
          value: "192.168.49.2"
        - name: "app"
          type: "A"
          value: "192.168.49.2"
  
  reverse_zones:
    "49.168.192.in-addr.arpa":
      ttl: 604800
      serial: 2
      admin: "admin.test.local"
      ns: "ns1.test.local"
      records:
        - name: "2"
          type: "PTR"
          value: "ns1.test.local."
        - name: "2"
          type: "PTR"
          value: "web.test.local."

nodeSelector: {}
tolerations: []
affinity: {}

testPod:
  enabled: true
  image: alpine:latest
