apiVersion: v2
name: mailstack
description: A Helm chart for complete email stack with mailserver and roundcube
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - email
  - mailserver
  - roundcube
  - smtp
  - imap

maintainers:
  - name: Giovanni
    email: admin@localtest.com

dependencies: []

annotations:
  category: Communication
