# Configuration globale
global:
  domain: localtest.com
  namespace: mailserver  # Ajoutez cette ligne
# Configuration du serveur mail
mailserver:
  enabled: true
  image:
    repository: mailserver/docker-mailserver
    tag: latest
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  # Configuration SSL
  ssl:
    type: ""  # Désactive SSL temporairement
    tlsLevel: "intermediate"
  
  # Configuration de la stratégie de déploiement
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  
  # Configuration des ressources
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  # Configuration des ports
  ports:
    smtp: 25
    imap: 143
    submission: 587
    imaps: 993
    smtps: 465
  
  # Configuration des volumes persistants
  persistence:
    mailData:
      enabled: true
      size: 2Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    mailState:
      enabled: true
      size: 1Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    mailLogs:
      enabled: true
      size: 1Gi
      storageClass: ""
      accessMode: ReadWriteOnce
  
  # Configuration des comptes email
  accounts:
    - email: user1@localtest.com
      password: password123
    - email: user2@localtest.com
      password: password123
  
  # Configuration des alias
  aliases:
    - alias: admin@localtest.com
      target: user1@localtest.com
  
  # Service configuration
  service:
    type: ClusterIP
    annotations: {}

# Configuration Roundcube
roundcube:
  enabled: true
  
  # Configuration pour roundcube1
  instance1:
    enabled: true
    name: roundcube1
    replicaCount: 1
    
    image:
      repository: roundcube/roundcubemail
      tag: latest
      pullPolicy: IfNotPresent
    
    # Configuration spécifique
    config:
      dbType: sqlite
      desKey: rcube-session-key-user1-12345678901234567890
      uploadMaxFilesize: 10M
    
    # Configuration des ressources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
    
    # Persistence
    persistence:
      enabled: true
      size: 500Mi
      storageClass: ""
      accessMode: ReadWriteOnce
    
    # Service
    service:
      type: NodePort
      port: 80
      nodePort: 31080
      annotations: {}
  
  # Configuration pour roundcube2
  instance2:
    enabled: true
    name: roundcube2
    replicaCount: 1
    
    image:
      repository: roundcube/roundcubemail
      tag: latest
      pullPolicy: IfNotPresent
    
    # Configuration spécifique
    config:
      dbType: sqlite
      desKey: rcube-session-key-user2-98765432109876543210
      uploadMaxFilesize: 10M
    
    # Configuration des ressources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
    
    # Persistence
    persistence:
      enabled: true
      size: 500Mi
      storageClass: ""
      accessMode: ReadWriteOnce
    
    # Service
    service:
      type: NodePort
      port: 80
      nodePort: 31081
      annotations: {}

# Configuration des ConfigMaps
configMap:
  enabled: true

# Configuration des Secrets
secret:
  enabled: true

# Annotations communes
commonAnnotations: {}

# Labels communs
commonLabels: {}

# Configuration des NodeSelector
nodeSelector: {}

# Configuration des tolerations
tolerations: []

# Configuration de l'affinité
affinity: {}
