image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

# ⚠️ DOIT être défini (via --set mysqlRootPassword=...)
mysqlRootPassword: "MotDePasseFort"

# Optionnels : création auto au démarrage
mysqlDatabase: ""
# SUPPRIMEZ ou COMMENTEZ ces deux lignes problématiques :
# mysqlUser: "root"
# mysqlPassword: "MotDePasseFort"

# OU créez un utilisateur régulier à la place :
mysqlUser: "appuser"  # Nom d'utilisateur régulier
mysqlPassword: "MotDePasseFort"

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: "standard"
  size: 1Gi

resources:
  limits:
    memory: 512Mi
    cpu: 250m
  requests:
    memory: 256Mi
    cpu: 100m

nodeSelector: {}
tolerations: []
affinity: {}
