github:
  owner: giov2002
  repo: helm-web-services-charts
  branch: main

ci_cd:
  ci:
    workflow: helm-full-check.yml

paths:
  helm_charts: ".."

services:
  bind9:
    priority: 1
  mysql:
    priority: 2
  phpmyadmin:
    priority: 3
  email:
    priority: 4
  monitoring:
    priority: 5
  unbound:
    priority: 6
  web-apache:
    priority: 7
  web-nginx:
    priority: 8

project_environment:
  platform: Minikube
