---
- name: Ping all Kubernetes nodes
  hosts: all
  gather_facts: yes
  tasks:
    - name: Test connectivity to nodes
      ansible.builtin.ping:

    - name: Display node information
      ansible.builtin.debug:
        msg: |
          Node: {{ inventory_hostname }}
          IP: {{ ansible_host }}
          Status: SUCCESS
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}