# Configuration principale du chart mailstack
global:
  namespace: email-stack

# Labels et annotations communes
commonLabels:
  app.kubernetes.io/part-of: mailstack

commonAnnotations:
  description: "Complete email stack with mailserver and roundcube"

# Configuration du serveur mail
mailserver:
  enabled: true
  
  image:
    repository: ghcr.io/docker-mailserver/docker-mailserver
    tag: "13.3.1"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  # Ports du serveur mail
  ports:
    smtp: 25
    imap: 143
    imaps: 993
    submission: 587
    smtps: 465
  
  # Configuration du service
  service:
    type: ClusterIP
    annotations: {}
  
  # Comptes email (utilisateurs) créés au déploiement
  accounts:
    - email: "postmaster@mail.local"
      password: "postmaster123"
    - email: "user1@mail.local"
      password: "password123"
    - email: "user2@mail.local"
      password: "password456"
    - email: "jojo@mail.local"
      password: "jojo"
    - email: "smith@mail.local"
      password: "smith"
    - email: "aurelien@mail.local"
      password: "aurelien"
    - email: "fitahiana@mail.local"
      password: "fitahiana"
    - email: "nanja@mail.local"
      password: "nanja"
    - email: "lalaina@mail.local"
      password: "lalaina"
    - email: "harivony@mail.local"
      password: "harivony"
  
  # Comptes email supplémentaires (optionnel)
  extraAccounts: |
    # bob@mail.local|{PLAIN}motdepasseBob
  
  # Alias email
  aliases:
    - alias: "admin@mail.local"
      target: "user1@mail.local"
  
  # Configuration des volumes
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 10Gi
  
  # Variables d'environnement
  env:
    HOSTNAME: "mailserver.mail.local"
    DOMAINNAME: "mail.local"
    POSTFIX_INET_PROTOCOLS: "ipv4"
    ONE_DIR: "1"
    ENABLE_RSPAMD: "0"
    ENABLE_CLAMAV: "0"
    ENABLE_FAIL2BAN: "0"
    ENABLE_AMAVIS: "0"
    PERMIT_DOCKER: "connected-networks"
    OVERRIDE_HOSTNAME: "mailserver.mail.local"
    
    # Configuration Relay Gmail
    RELAY_HOST: "smtp.gmail.com"
    RELAY_PORT: "587"
    RELAY_USER: "rakotonirinatafaragiovanni@gmail.com"
    RELAY_PASSWORD: "yvtk bvxn udam dwkn"
  
  # Ressources
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Configuration Roundcube
roundcube:
  enabled: true
  
  # Instance unique Roundcube
  instance1:
    enabled: true
    name: "roundcube"
    replicaCount: 1
    
    image:
      repository: roundcube/roundcubemail
      tag: "1.6.11-apache"
      pullPolicy: IfNotPresent
    
    config:
      dbType: "sqlite"
      uploadMaxFilesize: "20M"
      desKey: "rcmail-user1-des-key-12345678901234567890"
    
    service:
      type: NodePort
      port: 80
      nodePort: 30081
      annotations: {}
    
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 2Gi
    
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  
  # Instance 2 désactivée
  instance2:
    enabled: false

# Secret pour les comptes
secret:
  enabled: true

# Configuration Haute Disponibilité
# Les pods peuvent tourner sur smtp1 et smtp3 uniquement
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist

tolerations: []