{{- if .Values.mailserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mailstack.mailserver.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.mailserver.replicaCount }}
  strategy:
    type: {{ .Values.mailserver.strategy.type }}
    {{- if eq .Values.mailserver.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.mailserver.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.mailserver.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "mailstack.mailserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mailstack.mailserver.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostname: mail
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mailserver
        image: "{{ .Values.mailserver.image.repository }}:{{ .Values.mailserver.image.tag }}"
        imagePullPolicy: {{ .Values.mailserver.image.pullPolicy }}
        ports:
        - name: smtp
          containerPort: {{ .Values.mailserver.ports.smtp }}
          protocol: TCP
        - name: imap
          containerPort: {{ .Values.mailserver.ports.imap }}
          protocol: TCP
        - name: submission
          containerPort: {{ .Values.mailserver.ports.submission }}
          protocol: TCP
        - name: imaps
          containerPort: {{ .Values.mailserver.ports.imaps }}
          protocol: TCP
        - name: smtps
          containerPort: {{ .Values.mailserver.ports.smtps }}
          protocol: TCP
        env:
        - name: SSL_TYPE
          value: "{{ .Values.mailserver.ssl.type }}"
        - name: TLS_LEVEL
          value: "{{ .Values.mailserver.ssl.tlsLevel }}"
        - name: PERMIT_DOCKER
          value: "container"
        - name: ONE_DIR
          value: "1"
        - name: ENABLE_CLAMAV
          value: "0"
        - name: ENABLE_SPAMASSASSIN
          value: "0"
        - name: ENABLE_FAIL2BAN
          value: "0"
        - name: ENABLE_POSTGREY
          value: "0"
        - name: OVERRIDE_HOSTNAME
          value: "mail.{{ .Values.global.domain }}"
        envFrom:
        - configMapRef:
            name: mail-config
        volumeMounts:
        - name: mail-data
          mountPath: /var/mail
        - name: mail-state
          mountPath: /var/mail-state
        - name: mail-logs
          mountPath: /var/log/mail
        - name: mail-config-volume
          mountPath: /tmp/docker-mailserver
        resources:
          {{- toYaml .Values.mailserver.resources | nindent 10 }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_PTRACE
      volumes:
      - name: mail-data
        {{- if .Values.mailserver.persistence.mailData.enabled }}
        persistentVolumeClaim:
          claimName: mail-data
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: mail-state
        {{- if .Values.mailserver.persistence.mailState.enabled }}
        persistentVolumeClaim:
          claimName: mail-state
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: mail-logs
        {{- if .Values.mailserver.persistence.mailLogs.enabled }}
        persistentVolumeClaim:
          claimName: mail-logs
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: mail-config-volume
        secret:
          secretName: mail-accounts
{{- end }}
