name: 🔍 Vérification Charts Helm

# Quand se déclencher : seulement quand on modifie les charts
on:
  push:
    paths:
      - 'charts/**'  # Seulement si quelque chose change dans le dossier charts/
  pull_request:
    paths:
      - 'charts/**'

jobs:
  check-helm-charts:
    name: Vérifier les Charts Helm
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu gratuite
    
    steps:
    # 1️⃣ Récupérer votre code depuis GitHub
    - name: 📥 Récupérer le code
      uses: actions/checkout@v4

    # 2️⃣ Installer Helm sur la machine virtuelle
    - name: ⚙️ Installer Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    # 3️⃣ Vérifier le chart web-nginx
    - name: 🔍 Vérifier web-nginx
      run: |
        echo "=== Vérification du chart web-nginx ==="
        echo "📁 Fichiers dans le chart :"
        ls -la charts/web-nginx/
        
        echo "🔍 Lint du chart (recherche d'erreurs) :"
        helm lint charts/web-nginx/
        
        echo "🧪 Test de génération des templates :"
        helm template test-nginx charts/web-nginx/ --dry-run

    # 4️⃣ Vérifier le chart monitoring
    - name: 🔍 Vérifier monitoring
      run: |
        echo "=== Vérification du chart monitoring ==="
        echo "📁 Fichiers dans le chart :"
        ls -la charts/monitoring/monitoring-chart/
        
        echo "🔍 Lint du chart (recherche d'erreurs) :"
        helm lint charts/monitoring/monitoring-chart/
        
        echo "🧪 Test de génération des templates :"
        helm template test-monitoring charts/monitoring/monitoring-chart/ --dry-run

    # 5️⃣ Résumé final
    - name: ✅ Résumé
      run: |
        echo "🎉 Tous les checks sont passés !"
        echo "Vos charts Helm sont valides et prêts à être déployés."
