apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "bind9.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "bind9.selectorLabels" . | nindent 4 }}
  ports:
  - name: dns-udp
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: UDP
  - name: dns-tcp
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
  type: {{ .Values.service.type }}
